-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.orders
(
    order_id serial NOT NULL,
    date_placed date DEFAULT NOW(),
    status character varying(64) NOT NULL,
    user_id integer default NULL,
    PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    username character varying(64) NOT NULL UNIQUE,
    password character varying(64) NOT NULL,
    role character varying(12) NOT NULL,
    PRIMARY KEY (user_id)
    );

ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

CREATE TABLE IF NOT EXISTS public.tag_materiale (
    id serial NOT NULL,
    materiale character varying(64) NOT NULL,
    tag_type character varying(64) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO public.dimensioner_bredde (bredde, id)
VALUES
    (270, 1),
    (300, 2),
    (330, 3),
    (360, 4),
    (390, 5),
    (420, 6),
    (450, 7),
    (480, 8),
    (510, 9),
    (540, 10),
    (570, 11),
    (600, 12);

INSERT INTO public.dimensioner_længde (længde, id)
VALUES
    (270, 1),
    (300, 2),
    (330, 3),
    (360, 4),
    (390, 5),
    (420, 6),
    (450, 7),
    (480, 8),
    (510, 9),
    (540, 10),
    (570, 11),
    (600, 12),
    (630, 13),
    (660, 14),
    (690, 15),
    (720, 16),
    (750, 17),
    (780, 18);

INSERT INTO public.tag_materiale (materiale, tag_type)
VALUES
    ('Sunlux 1300K', 'Fladt'),
    ('Sunlux 1200N', 'Fladt'),
    ('Benders sort', 'Skrå'),
    ('Benders brun', 'Skrå'),
    ('Benders tegldrød', 'Skrå'),
    ('Benders rød', 'Skrå'),
    ('Eternit grå B6', 'Skrå');

INSERT INTO public.skur (id,skur)
VALUES
    (1,Ja),
    (2,Nej);

INSERT INTO public.spær_og_rem (id,materiale)
VALUES
    (1,'Benders sort'),
    (2,'Benders brun'),
    (3,'Benders tegldrød'),
    (4,'Benders rød'),
    (5,'Eternit grå B6');

END;